/**
 * QuantumEnergyOS - iOS C Interface Header
 *
 * This header exports the C-compatible functions generated by UniFFI
 * from the Rust quantum kernel. It can be included by:
 *
 * - Swift code (via bridging header)
 * - Objective-C native modules
 * - C/C++ code directly
 *
 * All strings returned by these functions must be freed with free().
 * Opaque handle type represents a QuantumEnergyOS instance.
 */

#ifndef QuantumEnergyOS_h
#define QuantumEnergyOS_h

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

// Forward declarations of Rust-generated data structures
// These are defined in quantum_energy_os.h (UniFFI generated)
struct quantum_energy_os_SimulationParameters;
struct quantum_energy_os_SimulationResult;
struct quantum_energy_os_PowerGridMetrics;
struct quantum_energy_os_Cuarzo4DState;
struct quantum_energy_os_String;
struct quantum_energy_os_array_double;

// Opaque handle to QuantumEnergyOS instance (defined by UniFFI in quantum_energy_os.h)
#ifndef quantum_energy_os_QuantumEnergyOSHandle
typedef struct quantum_energy_os_QuantumEnergyOSHandle quantum_energy_os_QuantumEnergyOSHandle;
#endif

// Rust call status (for error reporting)
typedef enum {
    RustCallStatus_OK = 0,
    RustCallStatus_ERROR = 1,
    RustCallStatus_PANIC = 2
} RustCallStatus;

// ============================================================================
// CONSTRUCTOR / DESTRUCTOR
// ============================================================================

/**
 * Create a new QuantumEnergyOS instance
 *
 * @param config_path Path to JSON configuration file (can be NULL for defaults)
 * @param enable_photonic_bridge Enable photonic-bridge hardware acceleration
 * @param out_status Output status code
 * @return Opaque handle (non-NULL on success, NULL on failure)
 */
quantum_energy_os_QuantumEnergyOSHandle quantum_energy_os_create_quantum_energy_os(
    const char* config_path,
    bool enable_photonic_bridge,
    RustCallStatus* out_status
);

/**
 * Destroy QuantumEnergyOS instance and free resources
 *
 * @param handle Instance handle (NULL-safe)
 */
void quantum_energy_os_shutdown(
    quantum_energy_os_QuantumEnergyOSHandle handle
);

// ============================================================================
// SCENARIO OPTIMIZATION
// ============================================================================

/**
 * Optimize a single longevity simulation scenario
 *
 * @param handle Instance handle
 * @param params_json Serialized SimulationParameters JSON string
 * @param out_result Output SimulationResult structure (allocated by UniFFI)
 * @param out_status Status code
 *
 * @note: Caller must free out_result using quantum_energy_os_SimulationResult_free()
 */
void quantum_energy_os_optimize_scenario(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const char* params_json,
    struct quantum_energy_os_SimulationResult* out_result,
    RustCallStatus* out_status
);

/**
 * Batch optimization using photonic bridge parallelization
 *
 * @param handle Instance handle
 * @param scenarios_json Serialized array of SimulationParameters JSON
 * @param out_result_list Output list of SimulationResult structures
 * @param out_status Status code
 */
void quantum_energy_os_batch_optimize_photonic(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const char* scenarios_json,
    struct quantum_energy_os_SimulationResultList* out_result_list,
    RustCallStatus* out_status
);

// ============================================================================
// POWER GRID OPTIMIZATION (<1ms TARGET)
// ============================================================================

/**
 * Real-time power grid optimization
 *
 * Optimizes power distribution in sub-1ms latency. This function is
 * optimized for real-time response and uses photonic-bridge acceleration
 * when available.
 *
 * @param handle Instance handle
 * @param grid_json Current PowerGridMetrics as JSON string
 * @param weights_json Constraint weightings (JSON map: "cost" -> weight, etc.)
 * @param out_optimized Optimized PowerGridMetrics output structure
 * @param out_status Status code
 */
void quantum_energy_os_optimize_power_grid_realtime(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const char* grid_json,
    const char* weights_json,
    struct quantum_energy_os_PowerGridMetrics* out_optimized,
    RustCallStatus* out_status
);

// ============================================================================
// CUARZO 4D HOLOGRAPHIC VISUALIZATION
// ============================================================================

/**
 * Get current Cuarzo 4D holographic storage state
 *
 * Returns the 4D spatial dimensions, resolution, and wave interference
 * pattern state for real-time visualization with react-native-skia.
 *
 * @param handle Instance handle
 * @param out_state Cuarzo4DState structure
 * @param out_status Status code
 */
void quantum_energy_os_get_cuarzo_4d_state(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    struct quantum_energy_os_Cuarzo4DState* out_state,
    RustCallStatus* out_status
);

/**
 * Update Cuarzo storage dimensions and resolution
 *
 * @param handle Instance handle
 * @param new_dimensions 4-element array of f64 representing 4D space size
 * @param len Length of array (must be 4)
 * @param resolution_multiplier Factor to scale resolution (1.0 = native)
 * @param out_status Status code
 */
void quantum_energy_os_update_cuarzo_dimensions(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const struct quantum_energy_os_array_double* new_dimensions,
    double resolution_multiplier,
    RustCallStatus* out_status
);

// ============================================================================
// QUANTUM SECURITY (SECURE ENCLAVE / KEYSTORE)
// ============================================================================

/**
 * Generate quantum-resistant keypair
 *
 * Generates Ed25519 or X25519 keypair, optionally storing private key
 * in platform secure enclave (iOS) or Android Keystore.
 *
 * @param handle Instance handle
 * @param key_type "ed25519" or "x25519"
 * @param use_secure_enclave True for Secure Enclave/Keystore storage
 * @param out_key_id Output key identifier string (for later retrieval)
 * @param out_status Status code
 */
void quantum_energy_os_generate_quantum_keypair(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const char* key_type,
    bool use_secure_enclave,
    struct quantum_energy_os_String* out_key_id,
    RustCallStatus* out_status
);

/**
 * Verify quantum-resistant signature
 *
 * @param handle Instance handle
 * @param message Original message (UTF-8 bytes)
 * @param signature Base64-encoded Ed25519 signature
 * @param public_key_id Key identifier previously generated
 * @param out_valid Output boolean indicating signature validity
 * @param out_status Status code
 */
void quantum_energy_os_verify_quantum_signature(
    quantum_energy_os_QuantumEnergyOSHandle handle,
    const char* message,
    const char* signature,
    const char* public_key_id,
    bool* out_valid,
    RustCallStatus* out_status
);

// ============================================================================
// UTILITY FUNCTIONS (JSON SERIALIZATION)
// ============================================================================

/**
 * Serialize SimulationResult to JSON string
 * Caller must free returned string with free().
 */
char* quantum_energy_os_SimulationResult_to_json(
    const struct quantum_energy_os_SimulationResult* result
);

/**
 * Serialize PowerGridMetrics to JSON string
 */
char* quantum_energy_os_PowerGridMetrics_to_json(
    const struct quantum_energy_os_PowerGridMetrics* metrics
);

/**
 * Serialize Cuarzo4DState to JSON string
 */
char* quantum_energy_os_Cuarzo4DState_to_json(
    const struct quantum_energy_os_Cuarzo4DState* state
);

/**
 * Deserialize SimulationParameters from JSON string
 * Returns parsed parameters structure.
 */
struct quantum_energy_os_SimulationParameters quantum_energy_os_SimulationParameters_from_json(
    const char* json,
    RustCallStatus* out_status
);

/**
 * Serialize list of SimulationResult to JSON array
 */
char* quantum_energy_os_SimulationResultList_to_json(
    const struct quantum_energy_os_SimulationResultList* list
);

// ============================================================================
// STRING UTILITIES
// ============================================================================

/**
 * Free a string allocated by UniFFI/Rust
 */
void quantum_energy_os_string_free(struct quantum_energy_os_String* s);

#ifdef __cplusplus
}
#endif

#endif /* QuantumEnergyOS_h */