/**
 * QuantumEnergyOS - React Native TypeScript Bindings
 * Generated by UniFFI from quantum_energy_bridge.udl
 *
 * This file provides TypeScript definitions for the Rust quantum kernel
 * enabling high-performance quantum optimization in React Native.
 *
 * @package QuantumEnergyOS
 * @since 1.0.0
 */

// ============================================================================
// ENUMS
// ============================================================================

export enum ScenarioType {
  Base = "Base",
  IntervencionCalico = "IntervencionCalico",
  Optimista = "Optimista",
}

export enum QuantumAlgorithm {
  QAOAV16 = "QAOAV16",
  VQE35 = "VQE35",
  HybridQAOA = "HybridQAOA",
  PhotonicBridge = "PhotonicBridge",
}

// ============================================================================
// DATA RECORDS
// ============================================================================

/**
 * Parameters for quantum optimization simulation
 */
export interface SimulationParameters {
  // Biological/demographic parameters
  expectativa_vida_base: number;
  tasa_envejecimiento: number;
  poblacion_inicial: number;
  years_to_simulate: number;

  // Quantum optimization configuration
  quantum_algorithm: QuantumAlgorithm;
  optimization_iterations: number;
  convergence_threshold: number;

  // Photonic bridge settings
  photonic_bridge_enabled: boolean;
  bridge_latency_ms: number;
  parallelism_factor: number;
}

/**
 * Results from a quantum optimization run
 */
export interface SimulationResult {
  // Core outputs
  poblacion_futura: number;
  expectativa_vida_optimizada: number;
  tasa_mortalidad_ajustada: number;
  years_simulated: number;

  // Performance metrics
  optimization_time_ms: number;
  classical_compute_ms: number;
  quantum_advantage_factor: number;

  // Confidence intervals
  lower_bound_95: number;
  upper_bound_95: number;

  // Metadata
  algorithm_used: QuantumAlgorithm;
  timestamp_unix: number;
  scenario: ScenarioType;
}

/**
 * Power grid metrics for quantum optimization
 */
export interface PowerGridMetrics {
  total_power_mw: number;
  renewable_percentage: number;
  grid_efficiency: number;
  peak_load_mw: number;
  storage_capacity_mwh: number;
  quantum_optimized: boolean;
}

/**
 * Cuarzo 4D holographic storage state
 */
export interface Cuarzo4DState {
  dimensions: [number, number, number, number];
  data_points: number;
  resolution_scale: number;
  wave_interference_pattern: boolean;
  last_update_timestamp: number;
}

// ============================================================================
// UNIFFI-INTERFACE OBJECT
// ============================================================================

/**
 * QuantumEnergyOS - Main quantum optimization engine
 *
 * This is a UniFFI-generated interface to the Rust kernel.
 * Instance must be created via `createQuantumEnergyOS()` factory function.
 */
export interface QuantumEnergyOS {
  /**
   * Initialize the quantum kernel with configuration
   * @param configPath - Path to configuration file (JSON)
   * @param enablePhotonicBridge - Enable photonic-bridge acceleration
   * @returns true if initialization succeeded
   */
  init(configPath: string, enablePhotonicBridge: boolean): Promise<boolean>;

  /**
   * Run quantum optimization for longevity simulation
   * @param params - Optimization parameters
   * @returns Simulation results with quantum-optimized predictions
   */
  optimizeScenario(params: SimulationParameters): Promise<SimulationResult>;

  /**
   * Batch optimization using photonic-bridge parallel processing
   * @param scenarios - Array of simulation parameters
   * @returns Array of simulation results
   */
  batchOptimizePhotonic(scenarios: SimulationParameters[]): Promise<SimulationResult[]>;

  /**
   * Real-time power grid optimization (sub-1ms target)
   * @param gridMetrics - Current grid state
   * @param constraintWeightings - Optimization constraint priorities
   * @returns Optimized grid metrics
   */
  optimizePowerGridRealtime(
    gridMetrics: PowerGridMetrics,
    constraintWeightings: Record<string, number>
  ): Promise<PowerGridMetrics>;

  /**
   * Get current Cuarzo 4D holographic storage state
   * @returns Visualization state for 4D holographic rendering
   */
  getCuarzo4DState(): Promise<Cuarzo4DState>;

  /**
   * Update holographic storage configuration
   * @param newDimensions - New 4D space dimensions
   * @param resolutionMultiplier - Data resolution scaling factor
   */
  updateCuarzoDimensions(
    newDimensions: [number, number, number, number],
    resolutionMultiplier: number
  ): Promise<void>;

  /**
   * Generate quantum-resistant keypair (Ed25519/X25519)
   * @param keyType - "ed25519" or "x25519"
   * @param secureEnclave - Use platform secure enclave (iOS/Android)
   * @returns Encrypted key identifier stored in keystore
   */
  generateQuantumKeypair(keyType: string, secureEnclave: boolean): Promise<string>;

  /**
   * Verify quantum-resistant signature
   * @param message - Signed message
   * @param signature - Base64-encoded signature
   * @param publicKeyId - Key identifier from keystore
   * @returns true if signature is valid
   */
  verifyQuantumSignature(
    message: string,
    signature: string,
    publicKeyId: string
  ): Promise<boolean>;

  /**
   * Clean shutdown of quantum kernel
   */
  shutdown(): Promise<void>;
}

// ============================================================================
// FACTORY FUNCTION
// ============================================================================

/**
 * Create a new QuantumEnergyOS instance
 * This is the main entry point for the Rust quantum kernel
 *
 * @param configPath - Configuration file path (optional)
 * @param enablePhotonicBridge - Enable photonic hardware acceleration (optional)
 * @returns Promise resolving to QuantumEnergyOS instance
 *
 * @example
 * ```typescript
 * const quantumOS = await createQuantumEnergyOS(
 *   "/path/to/config.json",
 *   true  // photonic bridge enabled
 * );
 * ```
 */
export async function createQuantumEnergyOS(
  configPath?: string,
  enablePhotonicBridge?: boolean
): Promise<QuantumEnergyOS> {
  // This function will be implemented by the generated UniFFI binding
  // The actual implementation loads the native shared library (quantum_energy_os)
  // and instantiates the Rust QuantumKernel struct.

  // At runtime, this resolves to:
  // Android: com.quantumenergy.QuantumEnergyOSBridge.create()
  // iOS: QuantumEnergyOS.create()
  // Standalone: quantum_energy_os.QuantumEnergyOS.create()

  const effectivePath = configPath ?? "";
  const photonicEnabled = enablePhotonicBridge ?? false;

  // Dynamic loading of native module (implementation provided by UniFFI)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const QuantumEnergyOSModule = (await import('../native/quantum_energy_bridge')).default;

  return QuantumEnergyOSModule.createQuantumEnergyOS(
    effectivePath,
    photonicEnabled
  );
}

// ============================================================================
// TYPESCRIPT TYPE GUARDS
// ============================================================================

/**
 * Type guard for SimulationResult validation
 */
export function isValidSimulationResult(obj: unknown): obj is SimulationResult {
  if (typeof obj !== 'object' || obj === null) return false;
  const result = obj as Record<string, unknown>;
  return (
    typeof result.poblacion_futura === 'number' &&
    typeof result.expectativa_vida_optimizada === 'number' &&
    typeof result.optimization_time_ms === 'number' &&
    typeof result.algorithm_used === 'string'
  );
}

/**
 * Type guard for PowerGridMetrics validation
 */
export function isValidPowerGridMetrics(obj: unknown): obj is PowerGridMetrics {
  if (typeof obj !== 'object' || obj === null) return false;
  const result = obj as Record<string, unknown>;
  return (
    typeof result.total_power_mw === 'number' &&
    typeof result.grid_efficiency === 'number' &&
    typeof result.quantum_optimized === 'boolean'
  );
}

/**
 * Type guard for Cuarzo4DState validation
 */
export function isValidCuarzo4DState(obj: unknown): obj is Cuarzo4DState {
  if (typeof obj !== 'object' || obj === null) return false;
  const result = obj as Record<string, unknown>;
  return (
    Array.isArray(result.dimensions) &&
    result.dimensions.length === 4 &&
    typeof result.data_points === 'number' &&
    typeof result.resolution_scale === 'number'
  );
}

// ============================================================================
// REACT NATIVE HOOKS (Optional)
// ============================================================================

import { useEffect, useState, useCallback } from 'react';

/**
 * React Hook: useQuantumEnergyOS
 * Provides optimized quantum kernel instance with lifecycle management
 */
export function useQuantumEnergyOS(
  configPath?: string,
  enablePhotonicBridge?: boolean
): {
  quantumOS: QuantumEnergyOS | null;
  loading: boolean;
  error: Error | null;
  initialize: () => Promise<void>;
  shutdown: () => Promise<void>;
} {
  const [quantumOS, setQuantumOS] = useState<QuantumEnergyOS | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const initialize = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const instance = await createQuantumEnergyOS(configPath, enablePhotonicBridge);
      setQuantumOS(instance);
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)));
    } finally {
      setLoading(false);
    }
  }, [configPath, enablePhotonicBridge]);

  const shutdown = useCallback(async () => {
    if (quantumOS) {
      await quantumOS.shutdown();
      setQuantumOS(null);
    }
  }, [quantumOS]);

  // Auto-initialize on mount
  useEffect(() => {
    initialize();
    return () => {
      shutdown();
    };
  }, []);

  return { quantumOS, loading, error, initialize, shutdown };
}

/**
 * React Hook: useCuarzo4DVisualization
 * Manages Cuarzo 4D holographic visualization state
 */
export function useCuarzo4DVisualization(
  quantumOS: QuantumEnergyOS | null
): {
  cuarzoState: Cuarzo4DState | null;
  updateDimensions: (dims: [number, number, number, number], scale: number) => Promise<void>;
} {
  const [cuarzoState, setCuarzoState] = useState<Cuarzo4DState | null>(null);

  const updateDimensions = useCallback(async (dims: [number, number, number, number], scale: number) => {
    if (quantumOS) {
      await quantumOS.updateCuarzoDimensions(dims, scale);
      const newState = await quantumOS.getCuarzo4DState();
      setCuarzoState(newState);
    }
  }, [quantumOS]);

  // Poll for state updates (every 100ms for real-time vis)
  useEffect(() => {
    if (!quantumOS) return;

    const interval = setInterval(async () => {
      const state = await quantumOS.getCuarzo4DState();
      setCuarzoState(state);
    }, 100);

    return () => clearInterval(interval);
  }, [quantumOS]);

  return { cuarzoState, updateDimensions };
}

// ============================================================================
// EXPORTS
// ============================================================================

export type { QuantumEnergyOS };

// Default export for compatibility
export default {
  createQuantumEnergyOS,
  useQuantumEnergyOS,
  useCuarzo4DVisualization,
  ScenarioType,
  QuantumAlgorithm,
  SimulationParameters,
  SimulationResult,
  PowerGridMetrics,
  Cuarzo4DState,
  isValidSimulationResult,
  isValidPowerGridMetrics,
  isValidCuarzo4DState,
};